version: '2'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: service mongodb start && python /app/manage.py runserver 0.0.0.0:8000 &
    ports:
     - "8000:8000"
     - "6800:6800"
     - "80:80"
    volumes:
     - .:/app